config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :discounts, except: :update do
    member do
      post 'update', as: 'post_update'
    end
  end
  resources :products, except: :update do
    member do
      post 'update', as: 'post_update'
      put 'add_to_cart'
      put 'remove_from_cart'
    end
  end
end

app/models/cart.rb
class Cart < Ohm::Model
  attribute :subtotal
  list :products, Product
end

app/models/discount.rb
class Discount < Ohm::Model
  attribute :rebate
  attribute :product_amount

  reference :product, Product
end

app/models/product.rb
class Product < Ohm::Model
  attribute :name
  attribute :description
  attribute :price

  set :discounts, Discount

  def validate
    assert_presense :name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: [:show, :edit, :update, :destroy]

  def index
    @discounts = Discount.all.to_a
  end

  def show
  end

  def new
    @discount = Discount.new
  end

  def edit
  end

  def create
    @discount = Discount.new(discount_params)

    if @discount.save
      product = Product[params[:product]]
      product&.discounts&.add @discount

      redirect_to discounts_path, notice: 'Discount was successfully created.'
    else
      render :new
    end
  end

  def update
    if @discount.update(discount_params)
      redirect_to discounts_path, notice: 'Discount was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /discounts/1
  def destroy
    @discount.delete
    redirect_to discounts_url, notice: 'Discount was successfully destroyed.'
  end

  private
    def set_discount
      @discount = Discount[params[:id]]
    end

    def discount_params
      { product_amount: params[:product_amount], rebate: params[:rebate], product: Product[params[:product]&.to_i] }
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_cart, only: [:index, :add_to_cart, :remove_from_cart]

  def index
    @products = Product.all.to_a

    selected = Product.fetch(@cart.products.ids)
    uniq_selected = Product.fetch(Set.new(@cart.products.ids).to_a)

    @selected_products = uniq_selected.reduce([]) do |res, el|
      amount, price = calculate_discount.(el)
      res << { product: el, amount: amount, price: price }
    end

    @subtotal = selected.reduce(0) do |res, el|
      _, price, _ = calculate_discount.(el)
      res += price
    end
     p @cart.products.size

    @discount = selected.reduce(0) do |res, el|
      _, _, discount = calculate_discount.(el)
      res += discount.round
    end.to_f
  end

  def add_to_cart
    respond_to do |format|
      if @cart.products.push(Product[params[:id]])
        format.html { redirect_to products_path, notice: 'Product was successfully removed from cart' }
      end
    end
  end

  def remove_from_cart
    respond_to do |format|
      if @cart.products.delete(Product[params[:id]])
        format.html { redirect_to products_path, notice: 'Product was successfully added' }
      end
    end
  end


  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_path, notice: 'Product was successfully updated' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.delete
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product[params[:id]]
    end

    def calculate_discount
      lambda do |el|
        discount = Discount.fetch(el.discounts.ids)&.first
        discount_amount = discount&.product_amount.to_i
        amount = @cart.products.
                 ids.count(el.id)

        discount_part = if discount && amount >= discount_amount
                          (discount&.rebate.to_f / 100) * el.price.to_i
                        else
                          0
                        end

        price = if discount && amount >= discount_amount
                  el.price.to_f - discount_part.round
                else
                  el.price.to_f
                end
        [amount, price, discount_part]
      end
    end

    def set_cart
      @cart = Cart[1] || Cart.new.save
    end

    def product_params
      { name: params[:name], price: params[:price], description: params[:description] }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/discounts/_form.html.slim
.row
  .col.s12
    -if @discount.attributes != {}
      = form_tag post_update_discount_path(@discount.id), id: 'update_discount'
        .input-field
          = label_tag :rebate
          = text_field_tag :rebate, @discount.rebate
        .input-field
          = label_tag :product_amount
          = text_field_tag :product_amount, @discount.product_amount
        .input-field.s12
          = select_tag :product, options_for_select(Product.all.map{ |x| [x.name, x.id] }, @discount.product.id)
          = label_tag :product
        .actions
          = submit_tag nil, class: 'btn waves-effect waves-light'
            i.materialize-icon.white-text Submit
          = link_to :back, class: 'btn waves-effect waves-light'
            span.white-text Back
    - else
      = form_tag discounts_path, id: 'set_discount'
        .input-field
          = label_tag :rebate
          = text_field_tag :rebate, @discount.rebate
        .input-field
          = label_tag :product_amount
          = text_field_tag :product_amount, @discount.product_amount
        .input-field
          = select_tag :product, options_for_select(Product.all.to_a.map{ |x| [x.name, x.id] } )
          label Product
        .actions
          = submit_tag nil, class: 'btn waves-effect waves-light'
            i.materialize-icon.white-text Submit
          = link_to :back, class: 'btn waves-effect waves-light'
            span.white-text Back

app/views/discounts/edit.html.slim
h1
  | Editing Discount
= render 'form'

app/views/discounts/index.html.slim
p#notice
  = notice
h1
  | Listing Discounts
table
  thead
    tr
      th
        | Rebate
      th
        | Amount
      th
        | Product
      th[colspan="3"]
  tbody
    - @discounts.each do |discount|
      tr
        td
          = discount.rebate
        td
          = discount.product_amount
        td
          = discount.product&.name
        td
          = link_to 'Show', discount_path(discount.id)
        td
          = link_to 'Edit', edit_discount_path(discount.id)
        td
          = link_to 'Destroy', discount_path(discount.id), method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Discount', new_discount_path

app/views/discounts/new.html.slim
h1
  | New Discount
= render 'form'

app/views/discounts/show.html.slim
p#notice
  = notice
p
  strong
    | Rebate:
  = @discount.rebate
p
  strong
    | Amount:
  = @discount.product_amount
p
  strong
    | Product
  = @discount.product.name
= link_to 'Edit', edit_discount_path(@discount.id)
|  |
= link_to 'Back', discounts_path

app/views/layouts/application.slim
doctype html
html
  head
    title MateStore
    = stylesheet_link_tag  'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      = yield

app/views/products/_form.slim
.row
  .col.s12
    -if @product.attributes != {}
      = form_tag post_update_product_path(@product.id), id: 'update_product'
        .input-field
          = label_tag :name
          = text_field_tag :name, @product.name
        .input-field
          = label_tag :price
            span Price, $
          = text_field_tag :price, @product.price
        .input-field
          = label_tag :description
          = text_area_tag :description, @product.description, class: 'materialize-textarea'
        .actions
          = submit_tag nil, class: 'btn waves-effect waves-light'
            i.materialize-icon.white-text Submit
          = link_to :back, class: 'btn waves-effect waves-light'
            span.white-text Back
    - else
      = form_tag products_path, id: 'create_product'
        .input-field
          = label_tag :name
          = text_field_tag :name, @product.name
        .input-field
          = label_tag :price
            span Price, $
          = text_field_tag :price, @product.price
        .input-field
          = label_tag :description
          = text_area_tag :description, @product.description, class: 'materialize-textarea'
        .actions
          = submit_tag nil, class: 'btn waves-effect waves-light'
            i.materialize-icon.white-text Submit
          = link_to :back, class: 'btn waves-effect waves-light'
            span.white-text Back

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

app/views/products/index.slim
- if notice
  .card-panel.red#notice
    h6.white-text.center-align
      = notice
.row
  .col.s12.l12.m12
    h1.center-align All products
    p
      = link_to new_product_path, class: 'btn-floating btn-large waves-effect waves-light red'
        i.material-icons add
  .col.s12.l9.m9
    - @products.each do |product|
      .col.s12.l5.m6
        .card
          .card-image.waves-effect.waves-block.waves-light
            .col.s6
              img.activator src="http://www.healthyfig.com/wp-content/uploads/2015/06/Yerba-Mate1.jpg"
          .card-content
            span.card-title.activator.grey-text.text-darken-4
              =product.name
              i.material-icons.right more_vert
            p
              h5
                '$'
                =product.price
            p
              = link_to 'Edit', edit_product_path(product.id)
            p
              = link_to 'Add to cart', add_to_cart_product_path(product.id), method: :put
          .card-reveal
            span.card-title.grey-text.text-darken-4
              =product.name
              i.material-icons.right close
            p
              h5
                '$
                =product.price
            p
              = link_to 'Add to cart', add_to_cart_product_path(product.id), method: :put
            p
              = product.description
  .col.s12.l3.m3#cart-items.fixed
    ul.collection-with-header
      li.collection-header
        h4 Cart
        p
          | Subtotal
          span.secondary-content
            '$
            = @subtotal
        p
          | Discount
          span.secondary-content
            '$ -
            = @discount

        hr
      - @selected_products.each do |selected|
        li.collection-item
          span.title= selected[:product].name
          a.secondary-content
            span
              'X
              =selected[:amount]
          p
            '$
            = selected[:price]
            = link_to remove_from_cart_product_path(selected[:product].id), class: 'secondary-content waves-effect waves-circle waves-light btn-floating', method: :put
              i.material-icons clear
          hr

app/views/products/new.slim
h1 New Product
= render 'form'

app/views/products/show.slim
.card
  .card-image.waves-effect.waves-block.waves-light
    .col.s6
      img.activator src="http://www.healthyfig.com/wp-content/uploads/2015/06/Yerba-Mate1.jpg"
  .card-content
    span.card-title.activator.grey-text.text-darken-4
      =@product.name
      i.material-icons.right more_vert
    p
      h5
        '$'
        =@product.price
    p
      = link_to 'Edit', edit_product_path(@product.id)
      = link_to 'Back', products_path
  .card-reveal
    span.card-title.grey-text.text-darken-4
      =@product.name
      i.material-icons.right close
    p
      h5
        '$'
        =@product.price

    p
      = @product.description